### ISSUE TITLE
与直接把验证文件丢进 source 文件夹并跳过渲染有何区别？

### ISSUE THREAD

**Issue by forliuyifei** [rqh656418510/hexo-site-auth#1]
如题👆

**Comment by rqh656418510** [comment]
> 如题

两者的结果都一样，Hexo 构建后都会自动生成（或拷贝）对应的验证文件到 public 目录下，只是为了方便统一管理站点的验证信息，才特意写了该插件。

**Comment by forliuyifei** [comment]
> > 如题
> 
> 两者的结果都一样，Hexo 构建后都会自动生成（或拷贝）对应的验证文件到 public 目录下，只是为了方便统一管理站点的验证信息，才特意写了该插件。

所以还是稍稍影响 build 的速度吧，看来不适合我😅
